### ISSUE TITLE
PID: How to use it with DS18b20

### ISSUE THREAD

**Issue by martinmatias** [colinl/Sonoff-Tasmota#3]
Hi Colin, thanks for your PID code.
I have installed exactly your version and I'm using with one Relay and DS18b20 on wemos D1, that mean is configured as generic board (instead of TH10). Relay is not yet connected (no heater) and set temperature to 45 degrees, so I expect the relay always on, but it changes. I'm using 5.12 code from this fork of github (with last from arendst there is a compilation problem that I've not aaddresed yet) with user "user_config.h" for one relay.
I've configured temperature usgin mqtt
`mosquitto_pub -h broker -t  cmnd/termostato/pid_sp -m   45`

Output from console is:
`04:59:34 MQT: stat/termostato/RESULT = {"PID_SP":"45"}
05:01:56 MQT: tele/termostato/STATE = {"Time":"2018-08-30T05:01:56","Uptime":"3T01:10:20","Vcc":2.984,"POWER":"OFF","Wifi":{"AP":1,"SSId":"miwifi","RSSI":92,"APMac":"C0:4A:00:B6:A4:0F"}}
05:01:56 PID_Show_Sensor: mqtt_data: {"Time":"2018-08-30T05:01:56","DS18B20":{"Temperature":23.5},"TempUnit":"C"}
05:01:56 PID_Show_Sensor: Temperature: 23.5
05:01:56 MQT: tele/termostato/SENSOR = {"Time":"2018-08-30T05:01:56","DS18B20":{"Temperature":23.5},"TempUnit":"C"}
05:01:56 MQT: tele/termostato/PID = {"power":"1.000"}
05:01:57 MQT: stat/termostato/RESULT = {"POWER":"ON"}
05:01:57 MQT: stat/termostato/POWER = ON
05:02:00 MQT: tele/termostato/UPTIME = {"Time":"2018-08-30T05:02:00","Uptime":"3T01:10:24"}
05:03:57 MQT: stat/termostato/RESULT = {"POWER":"OFF"}
05:03:57 MQT: stat/termostato/POWER = OFF
05:06:57 MQT: tele/termostato/STATE = {"Time":"2018-08-30T05:06:57","Uptime":"3T01:15:21","Vcc":3.045,"POWER":"OFF","Wifi":{"AP":1,"SSId":"miwifi","RSSI":84,"APMac":"C0:4A:00:B6:A4:0F"}}
05:06:57 PID_Show_Sensor: mqtt_data: {"Time":"2018-08-30T05:06:57","DS18B20":{"Temperature":23.7},"TempUnit":"C"}
05:06:57 PID_Show_Sensor: Temperature: 23.7
05:06:57 MQT: tele/termostato/SENSOR = {"Time":"2018-08-30T05:06:57","DS18B20":{"Temperature":23.7},"TempUnit":"C"}
05:06:57 MQT: tele/termostato/PID = {"power":"1.000"}
05:06:58 MQT: stat/termostato/RESULT = {"POWER":"ON"}
05:06:58 MQT: stat/termostato/POWER = ON
05:08:58 MQT: stat/termostato/RESULT = {"POWER":"OFF"}
05:08:58 MQT: stat/termostato/POWER = OFF`

What am I doing or interpreting wrong?
Thanks in advance
Regards

Martin

**Comment by colinl** [comment]
Hi
Can you post the settings you have got for the pid at the start of user_config.h (or override) please.

**Comment by martinmatias** [comment]
Hi Colin, below you can find attached complete file. I've changed the extension to .txt due to extention restriction.
Since it have a lot of part, I don't unrdestand what you mean by the "start of user_config.h"

[user_config.txt](https://github.com/colinl/Sonoff-Tasmota/files/2336990/user_config.txt)


Regards
Martin

**Comment by colinl** [comment]
Sorry, I usually put my extra bits in user config override, so they are at the start of that.  I use the override so I can keep user_config.h at the default (except for telling it to use the override file so if I update the Tasmota code I don't need to go in and make all my changes again, however the way you have done that is fine.
First I note that you have TELE_PERIOD set to 300 secs so it will only fetch a new process value every 5 mins.  Is that what you meant?  You also have  PID_MAX_INTERVAL set to 300 secs.  The result of that is that if the time between pv values is ever greater than 5 mins the algorithm will drop the power to the manual power setting (which you have a zero).  However that is not actually happening as it would be 5 mins after the previous pv value.  You should either reduce the tele period or increase the max interval though to make sure there is a bit of a gap between them I normally put max interval to a bit more than twice the period, then if it misses two samples for some reason it will switch the power off.  
That is not what is happening here though, you also have TIMEPROP_MAX_UPDATE_INTERVALS set to 2 minutes.  This parameter does a similar thing with the timeprop output, if it is not sent a new power value within that time then it drops the power back to TIMEPROP_FALLBACK_POWERS, which is zero. If you look at the output from the console (it is difficult to read as it has joined all the lines together for some reason) you will see that at 05:01:56 it got a pv value then you can see tele/termostato/PID = {"power":"1.000"}, which is the output from pid algorithm.  Then stat/termostato/RESULT = {"POWER":"ON"} which is the timprop algorithm setting the output.  Exactly 2 minutes later you can see it switch off again due to the effect of TIMEPROP_MAX_UPDATE_INTERVALS.  Then three minutes later the next pv comes in and it puts it on again, and so on.
I don't know what you are controlling so don't know what rate you want the sensor to run at.  For my room temperatures I usually run them at 60 seconds, setting it to that on yours would cure the problem above.
Another small point, I see you have set the derivative to 15 seconds. I suggest starting with it at zero, while trying to set things up I find it better to start with no derivative, it can easily confuse one when it comes to tuning the loop I find.

**Comment by martinmatias** [comment]
Hi Colin, excelent, thanks!!! I've tested you're reply and it worked fine. I'm still working on it, since I dont have heating system connected yet, I'm using my solder to heat the sensor.
I've also changed all values using mqtt, the only one that stay at default is: TIMEPROP_MAX_UPDATE_INTERVALS since I havent found the mqtt command.
So, I've changed other this way:

`mosquitto_pub -h 192.168.1.114 -t  cmnd/termostato/pid_sp -m   30`
`mosquitto_pub -h 192.168.1.114 -t  cmnd/termostato/pid_max_interval -m   60`
`mosquitto_pub -h 192.168.1.114 -t  cmnd/termostato/pid_td  -m 0`

Now it seems to work fine. Once I install it (I'm going on vacation, so need to wait) I'll put graphana chart (through openHAB) to check how it works.

For future, I have a project that need to control termperatura at 4 ovens at the same time. I know that code is prepared to drive up to 8 relays, but, how to match 4 different sensors?

Regards!
Martin

**Comment by colinl** [comment]
The timeprop constants have to be compiled in.
In fact I compile in the timeprop and pid constants, except those that change regularly like setpoint of course.  I have each of my devices on a different branch of a clone of the tasmotta source and then I can easily recover if I have to replace the device, for example.  I don't like using mqtt as then you have to remember what to set everything to if you have to.
The primary cause of the problem was that the tele period was less than TIMEPROP_MAX_UPDATE_INTERVALS and PID_MAX_INTERVAL.  You didn't need to change those, you needed to reduce the tele period. Or if you didn't want to do that then you needed to *increase* the others.

**Comment by colinl** [comment]
I don't know why github thinks the above commits affect this issue, there doesn't seem to be any logical reason to me.
